
import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
})
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })
 
async function main() {
  const events = [
    {
      title: 'Soft Power vol. 12',
      tagline: 'An all-night residency in three rooms.',
      description: 'Soft Power returns for its twelfth edition with a carefully curated lineup spanning techno, breaks and experimental club music. Three rooms, no headliners, no bullshit. The focus is on the floor and the people on it.',
      lineup: '23:59 — Opening set\n01:00 — Maara (Montréal)\n03:00 — Sugar Free (Lisboa)\n05:00 — Lyz Eim (resident)',
      date: new Date('2026-06-07T23:59:00'),
      venue: 'OHM',
      address: 'Köpenicker Str. 70, 10179 Berlin',
      category: 'Club',
      audience: 'Queer',
      tags: ['Techno', 'Breaks'],
      imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
      priceMin: 8,
      priceMax: 14,
      pricingModel: 'Sliding scale',
      capacity: 320,
      status: 'approved',
    },
    {
      title: 'Body Pressure',
      tagline: 'Movement, sweat, and no phones.',
      description: 'A FLINTA* only night focused on physical presence and collective movement. No phones policy strictly enforced. The music moves between gqom, afrobeats and UK funky. Come to dance, not to document.',
      date: new Date('2026-06-14T22:00:00'),
      venue: 'Trauma Bar und Kino',
      address: 'Revaler Str. 99, 10245 Berlin',
      category: 'Club',
      audience: 'FLINTA*',
      tags: ['Gqom', 'Breaks'],
      imageUrl: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800',
      priceMin: 10,
      priceMax: 18,
      pricingModel: 'Sliding scale',
      capacity: 150,
      status: 'approved',
    },
    {
      title: 'Zine Werkstatt',
      tagline: 'Make something with your hands.',
      description: 'A free workshop for anyone who wants to make a zine. Materials provided. No experience needed. We will go through layout, printing and binding. Bring your ideas, your feelings, your rage.',
      date: new Date('2026-06-10T17:00:00'),
      venue: 'Sameheads',
      address: 'Richardstr. 10, 12043 Berlin',
      category: 'Workshop',
      audience: 'FLINTA*',
      tags: ['Spoken word', 'Solidarity'],
      imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800',
      priceMin: 0,
      priceMax: 0,
      pricingModel: 'Free',
      capacity: 20,
      status: 'approved',
    },
    {
      title: 'Tender Frequencies',
      tagline: 'Ambient and drone in a candlelit space.',
      description: 'An intimate evening of ambient and drone music in a candlelit venue. Four artists, two hours, no talking. Come to listen properly. Limited capacity — arrive on time.',
      date: new Date('2026-06-28T20:00:00'),
      venue: 'Radial System',
      address: 'Holzmarktstr. 33, 10243 Berlin',
      category: 'Concert',
      audience: 'Queer',
      tags: ['Ambient'],
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
      priceMin: 12,
      priceMax: 20,
      pricingModel: 'Sliding scale',
      capacity: 60,
      status: 'approved',
    },
    {
      title: 'Drag Brunch at Sameheads',
      tagline: 'Eggs, coffee, and absolute chaos.',
      description: 'Sunday drag brunch with three performers, free coffee for the first hour and a DJ set that starts at noon and does not stop until everyone has left. FLINTA* and queer first at the door.',
      date: new Date('2026-06-22T11:00:00'),
      venue: 'Sameheads',
      address: 'Richardstr. 10, 12043 Berlin',
      category: 'Performance',
      audience: 'Queer',
      tags: ['Drag'],
      imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
      priceMin: 0,
      priceMax: 10,
      pricingModel: 'PWYC',
      capacity: 50,
      status: 'approved',
    },
    {
      title: 'Queer Shorts Berlin',
      tagline: 'An evening of short films by queer filmmakers.',
      description: 'A curated screening of short films made by queer and FLINTA* filmmakers from Berlin and beyond. Six films, one interval, no content warnings withheld. Discussion with two directors after the screening.',
      date: new Date('2026-06-12T19:30:00'),
      venue: 'Moviemento',
      address: 'Kottbusser Damm 22, 10967 Berlin',
      category: 'Cinema',
      audience: 'Queer',
      tags: ['Solidarity'],
      imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
      priceMin: 7,
      priceMax: 12,
      pricingModel: 'Sliding scale',
      capacity: 90,
      status: 'approved',
    },
    {
      title: 'Fehler und Risse',
      tagline: 'New works on paper, textile and found objects.',
      description: 'A group exhibition by five Berlin-based artists exploring failure, repair and the aesthetics of the unfinished. Works in paper, textile and found objects. Opening with drinks and a short performance at 19:00. Exhibition runs until July 5th.',
      date: new Date('2026-06-05T19:00:00'),
      venue: 'District Berlin',
      address: 'Bessemerstr. 2-14, 12103 Berlin',
      category: 'Exhibition',
      audience: 'All welcome',
      tags: ['Solidarity'],
      imageUrl: 'https://images.unsplash.com/photo-1531913764164-f85c52e6e654?w=800',
      priceMin: 0,
      priceMax: 0,
      pricingModel: 'Free',
      capacity: 120,
      status: 'approved',
    },
    {
      title: 'Embodied Boundaries',
      tagline: 'A workshop on consent and physical space.',
      description: 'A practical workshop on consent, personal boundaries and communication in physical space. Led by two somatic practitioners. Not a therapy session, not a lecture. Bring comfortable clothes and an open mind. FLINTA* only.',
      date: new Date('2026-06-18T16:00:00'),
      venue: 'Oyoun',
      address: 'Lucy-Lameck-Str. 32, 12049 Berlin',
      category: 'Workshop',
      audience: 'FLINTA*',
      tags: ['Solidarity'],
      imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
      priceMin: 5,
      priceMax: 20,
      pricingModel: 'Sliding scale',
      capacity: 25,
      status: 'approved',
    },
    {
      title: 'Nachtfalter',
      tagline: 'Experimental electronics and live visuals.',
      description: 'Three acts performing live electronics alongside projected visuals. The programme moves from harsh noise to delicate synthesis. No DJ sets, no laptops hidden behind screens — everything performed live and visible.',
      date: new Date('2026-06-26T21:00:00'),
      venue: 'Silent Green',
      address: 'Gerichtstr. 35, 13347 Berlin',
      category: 'Concert',
      audience: 'All welcome',
      tags: ['Ambient', 'Techno'],
      imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800',
      priceMin: 10,
      priceMax: 10,
      pricingModel: 'Fixed price',
      capacity: 200,
      status: 'approved',
    },
    {
      title: 'After the Archive',
      tagline: 'Documentary film and conversation.',
      description: 'A screening of a 90-minute documentary about the recovery of a lost queer archive from 1970s West Berlin, followed by a conversation with the director and one of the people featured in the film.',
      date: new Date('2026-07-02T19:00:00'),
      venue: 'Kino Central',
      address: 'Rosenthaler Str. 39, 10178 Berlin',
      category: 'Cinema',
      audience: 'Queer',
      tags: ['Spoken word', 'Solidarity'],
      imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800',
      priceMin: 8,
      priceMax: 8,
      pricingModel: 'Fixed price',
      capacity: 70,
      status: 'approved',
    },
    {
      title: 'Körper / Raum',
      tagline: 'Site-specific performance in an empty factory.',
      description: 'A site-specific performance piece by a collective of five dancers responding to the architecture of a former factory space in Lichtenberg. Two showings per night, 45 minutes each. Audience moves through the space.',
      date: new Date('2026-06-19T19:00:00'),
      venue: 'Alte Münze',
      address: 'Molkenmarkt 2, 10179 Berlin',
      category: 'Performance',
      audience: 'All welcome',
      tags: ['Drag'],
      imageUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800',
      priceMin: 12,
      priceMax: 20,
      pricingModel: 'Sliding scale',
      capacity: 40,
      status: 'approved',
    },
    {
      title: 'Voices from the Margin',
      tagline: 'Readings by FLINTA* writers of colour.',
      description: 'An evening of readings by five FLINTA* writers of colour based in Berlin. Poetry, short prose and one excerpt from an upcoming novel. Books available to buy directly from the authors. In English and German.',
      date: new Date('2026-06-24T19:30:00'),
      venue: 'Oyoun',
      address: 'Lucy-Lameck-Str. 32, 12049 Berlin',
      category: 'Reading',
      audience: 'FLINTA*',
      tags: ['Spoken word', 'Solidarity'],
      imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
      priceMin: 5,
      priceMax: 15,
      pricingModel: 'Sliding scale',
      capacity: 60,
      status: 'approved',
    },
  ]
 
  await prisma.event.deleteMany()
  console.log('Cleared existing events')
 
  for (const event of events) {
    await prisma.event.create({ data: event })
  }
 
  console.log('Seeded', events.length, 'events')
}
 
main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())